relativeURLs = true
title = "Mikey Jarrell"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Development Economist"
    logo = "profile.png" 
    
